sequenceDiagram
  participant participant_ExpoZoraIconFontProvider as ExpoZoraIconFontProvider
  participant participant_useFonts as useFonts
  participant_ExpoZoraIconFontProvider->>participant_useFonts: useFonts()
  participant_useFonts-->>participant_ExpoZoraIconFontProvider: return
