sequenceDiagram
  participant participant_resolveExpoRuntimeConfigPluginOutput as resolveExpoRuntimeConfigPluginOutput
  participant participant_resolveExpoRuntimeDependencyMap as resolveExpoRuntimeDependencyMap
  participant participant_resolveExpoRuntimeGeneratedAppOutput as resolveExpoRuntimeGeneratedAppOutput
  participant participant_resolveExpoRuntimeLayoutIntegration as resolveExpoRuntimeLayoutIntegration
  participant participant_resolveExpoRuntimeNativeOutput as resolveExpoRuntimeNativeOutput
  participant_resolveExpoRuntimeGeneratedAppOutput->>participant_resolveExpoRuntimeDependencyMap: resolveExpoRuntimeDependencyMap()
  participant_resolveExpoRuntimeDependencyMap-->>participant_resolveExpoRuntimeGeneratedAppOutput: return
  participant_resolveExpoRuntimeGeneratedAppOutput->>participant_resolveExpoRuntimeLayoutIntegration: resolveExpoRuntimeLayoutIntegration()
  participant_resolveExpoRuntimeLayoutIntegration-->>participant_resolveExpoRuntimeGeneratedAppOutput: return
  participant_resolveExpoRuntimeGeneratedAppOutput->>participant_resolveExpoRuntimeNativeOutput: resolveExpoRuntimeNativeOutput()
  participant_resolveExpoRuntimeNativeOutput->>participant_resolveExpoRuntimeConfigPluginOutput: resolveExpoRuntimeConfigPluginOutput()
  participant_resolveExpoRuntimeConfigPluginOutput-->>participant_resolveExpoRuntimeNativeOutput: return
  participant_resolveExpoRuntimeNativeOutput-->>participant_resolveExpoRuntimeGeneratedAppOutput: return
