graph LR
  module_src_barcodeScanRuntime_ts["src/barcodeScanRuntime.ts"]
  module_src_bundledMedia_index_ts["src/bundledMedia/index.ts"]
  module_src_bundledMediaRegistrySource_ts["src/bundledMediaRegistrySource.ts"]
  module_src_bundledMediaResolver_ts["src/bundledMediaResolver.ts"]
  module_src_componentRegistry_ts["src/componentRegistry.ts"]
  module_src_createExpoRuntimeRegistry_tsx["src/createExpoRuntimeRegistry.tsx"]
  module_src_expoActionBridge_ts["src/expoActionBridge.ts"]
  module_src_ExpoBarcodeScannerAdapter_tsx["src/ExpoBarcodeScannerAdapter.tsx"]
  module_src_ExpoRuntimeProviders_tsx["src/ExpoRuntimeProviders.tsx"]
  module_src_generatedAppOutput_ts["src/generatedAppOutput.ts"]
  module_src_generatedSources_ts["src/generatedSources.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_layoutIntegrationPlanning_ts["src/layoutIntegrationPlanning.ts"]
  module_src_mediaPicker_createExpoMediaPickerAdapter_ts["src/mediaPicker/createExpoMediaPickerAdapter.ts"]
  module_src_mediaPicker_documentPicker_ts["src/mediaPicker/documentPicker.ts"]
  module_src_mediaPicker_index_ts["src/mediaPicker/index.ts"]
  module_src_mediaPicker_mediaKinds_ts["src/mediaPicker/mediaKinds.ts"]
  module_src_mediaPicker_photoLibraryPicker_ts["src/mediaPicker/photoLibraryPicker.ts"]
  module_src_mediaPicker_readSelectedBytes_ts["src/mediaPicker/readSelectedBytes.ts"]
  module_src_mediaPicker_types_ts["src/mediaPicker/types.ts"]
  module_src_permissionRuntime_ts["src/permissionRuntime.ts"]
  module_src_planning_ts["src/planning.ts"]
  module_src_resolveExpoRuntimePlan_ts["src/resolveExpoRuntimePlan.ts"]
  export_BARCODE_SCAN_DEDUPE_WINDOW_MS["BARCODE_SCAN_DEDUPE_WINDOW_MS"]
  module_src_barcodeScanRuntime_ts --> export_BARCODE_SCAN_DEDUPE_WINDOW_MS
  export_BARCODE_SCANNER_TYPES["BARCODE_SCANNER_TYPES"]
  module_src_barcodeScanRuntime_ts --> export_BARCODE_SCANNER_TYPES
  export_BarcodeScanRecord["BarcodeScanRecord"]
  module_src_barcodeScanRuntime_ts --> export_BarcodeScanRecord
  export_ComponentRegistry["ComponentRegistry"]
  module_src_componentRegistry_ts --> export_ComponentRegistry
  export_createComponentRegistry["createComponentRegistry"]
  module_src_componentRegistry_ts --> export_createComponentRegistry
  export_createComponentRegistry -.-> export_ComponentRegistry
  export_createExpoBundledMediaResolver["createExpoBundledMediaResolver"]
  module_src_bundledMediaResolver_ts --> export_createExpoBundledMediaResolver
  export_createExpoBundledMediaResolver -.-> export_ExpoBundledMediaResolver
  export_createExpoBundledMediaResolver -.-> export_ExpoBundledMediaValue
  export_createExpoRuntimeRegistry["createExpoRuntimeRegistry"]
  module_src_createExpoRuntimeRegistry_tsx --> export_createExpoRuntimeRegistry
  export_createExpoRuntimeRegistry -.-> export_ComponentRegistry
  export_executeExpoRuntimeAction["executeExpoRuntimeAction"]
  module_src_expoActionBridge_ts --> export_executeExpoRuntimeAction
  export_executeExpoRuntimeAction -.-> export_ExecuteExpoRuntimeActionArgs
  export_ExecuteExpoRuntimeActionArgs["ExecuteExpoRuntimeActionArgs"]
  module_src_expoActionBridge_ts --> export_ExecuteExpoRuntimeActionArgs
  export_ExecuteExpoRuntimeActionArgs -.-> export_ExpoRuntimeActionHandlers
  export_ExecuteExpoRuntimeActionArgs -.-> export_ExpoRuntimeRouterLike
  export_ExecuteExpoRuntimeActionArgs -.-> export_ExpoRuntimeThemeMode
  export_ExpoBarcodeScannerAdapter["ExpoBarcodeScannerAdapter"]
  module_src_ExpoBarcodeScannerAdapter_tsx --> export_ExpoBarcodeScannerAdapter
  export_ExpoBarcodeScanResultLike["ExpoBarcodeScanResultLike"]
  module_src_barcodeScanRuntime_ts --> export_ExpoBarcodeScanResultLike
  export_ExpoBundledMediaRegistry["ExpoBundledMediaRegistry"]
  module_src_bundledMediaResolver_ts --> export_ExpoBundledMediaRegistry
  export_ExpoBundledMediaRegistrySourceEntry["ExpoBundledMediaRegistrySourceEntry"]
  module_src_bundledMediaRegistrySource_ts --> export_ExpoBundledMediaRegistrySourceEntry
  export_ExpoBundledMediaResolver["ExpoBundledMediaResolver"]
  module_src_bundledMediaResolver_ts --> export_ExpoBundledMediaResolver
  export_ExpoBundledMediaResolverArgs["ExpoBundledMediaResolverArgs"]
  module_src_bundledMediaResolver_ts --> export_ExpoBundledMediaResolverArgs
  export_ExpoBundledMediaValue["ExpoBundledMediaValue"]
  module_src_bundledMediaResolver_ts --> export_ExpoBundledMediaValue
  export_ExpoRuntimeActionHandlerArgs["ExpoRuntimeActionHandlerArgs"]
  module_src_expoActionBridge_ts --> export_ExpoRuntimeActionHandlerArgs
  export_ExpoRuntimeActionHandlers["ExpoRuntimeActionHandlers"]
  module_src_expoActionBridge_ts --> export_ExpoRuntimeActionHandlers
  export_ExpoRuntimeAdapterId["ExpoRuntimeAdapterId"]
  module_src_resolveExpoRuntimePlan_ts --> export_ExpoRuntimeAdapterId
  export_ExpoRuntimeConfigPluginOutput["ExpoRuntimeConfigPluginOutput"]
  module_src_generatedAppOutput_ts --> export_ExpoRuntimeConfigPluginOutput
  export_ExpoRuntimeDependencyMap["ExpoRuntimeDependencyMap"]
  module_src_generatedAppOutput_ts --> export_ExpoRuntimeDependencyMap
  export_ExpoRuntimeGeneratedAppOutputPlan["ExpoRuntimeGeneratedAppOutputPlan"]
  module_src_generatedAppOutput_ts --> export_ExpoRuntimeGeneratedAppOutputPlan
  export_ExpoRuntimeGeneratedAppOutputPlan -.-> export_ExpoRuntimeLayoutIntegrationPlan
  export_ExpoRuntimeGeneratedAppOutputPlan -.-> export_ExpoRuntimeNativeOutputPlan
  export_ExpoRuntimeLayoutIntegrationPlan["ExpoRuntimeLayoutIntegrationPlan"]
  module_src_layoutIntegrationPlanning_ts --> export_ExpoRuntimeLayoutIntegrationPlan
  export_ExpoRuntimeNativeOutputPlan["ExpoRuntimeNativeOutputPlan"]
  module_src_generatedAppOutput_ts --> export_ExpoRuntimeNativeOutputPlan
  export_ExpoRuntimeNativeOutputPlan -.-> export_ExpoRuntimeConfigPluginOutput
  export_ExpoRuntimePlan["ExpoRuntimePlan"]
  module_src_resolveExpoRuntimePlan_ts --> export_ExpoRuntimePlan
  export_ExpoRuntimePlan -.-> export_ExpoBarcodeScannerAdapter
  export_ExpoRuntimeProviderId["ExpoRuntimeProviderId"]
  module_src_resolveExpoRuntimePlan_ts --> export_ExpoRuntimeProviderId
  export_ExpoRuntimeProviders["ExpoRuntimeProviders"]
  module_src_ExpoRuntimeProviders_tsx --> export_ExpoRuntimeProviders
  export_ExpoRuntimeProviders -.-> export_ExpoRuntimeProvidersProps
  export_ExpoRuntimeProvidersProps["ExpoRuntimeProvidersProps"]
  module_src_ExpoRuntimeProviders_tsx --> export_ExpoRuntimeProvidersProps
  export_ExpoRuntimeRouteResolution["ExpoRuntimeRouteResolution"]
  module_src_expoActionBridge_ts --> export_ExpoRuntimeRouteResolution
  export_ExpoRuntimeRouterLike["ExpoRuntimeRouterLike"]
  module_src_expoActionBridge_ts --> export_ExpoRuntimeRouterLike
  export_ExpoRuntimeThemeMode["ExpoRuntimeThemeMode"]
  module_src_expoActionBridge_ts --> export_ExpoRuntimeThemeMode
  export_getExpoBarcodeScannerViewSource["getExpoBarcodeScannerViewSource"]
  module_src_generatedSources_ts --> export_getExpoBarcodeScannerViewSource
  export_getExpoBundledMediaRegistrySource["getExpoBundledMediaRegistrySource"]
  module_src_bundledMediaRegistrySource_ts --> export_getExpoBundledMediaRegistrySource
  export_getExpoBundledMediaRegistrySource -.-> export_ExpoBundledMediaRegistrySourceEntry
  export_mapPermissionStatusToCameraPermissionStatus["mapPermissionStatusToCameraPermissionStatus"]
  module_src_barcodeScanRuntime_ts --> export_mapPermissionStatusToCameraPermissionStatus
  export_normalizeExpoBarcodeScanResult["normalizeExpoBarcodeScanResult"]
  module_src_barcodeScanRuntime_ts --> export_normalizeExpoBarcodeScanResult
  export_normalizeExpoBarcodeScanResult -.-> export_ExpoBarcodeScanResultLike
  export_resolveExpoBundledMediaAsset["resolveExpoBundledMediaAsset"]
  module_src_bundledMediaResolver_ts --> export_resolveExpoBundledMediaAsset
  export_resolveExpoBundledMediaAsset -.-> export_ExpoBundledMediaValue
  export_resolveExpoRuntimeConfigPluginOutput["resolveExpoRuntimeConfigPluginOutput"]
  module_src_generatedAppOutput_ts --> export_resolveExpoRuntimeConfigPluginOutput
  export_resolveExpoRuntimeConfigPluginOutput -.-> export_ExpoRuntimeConfigPluginOutput
  export_resolveExpoRuntimeConfigPluginOutput -.-> export_ExpoRuntimePlan
  export_resolveExpoRuntimeDependencyMap["resolveExpoRuntimeDependencyMap"]
  module_src_generatedAppOutput_ts --> export_resolveExpoRuntimeDependencyMap
  export_resolveExpoRuntimeDependencyMap -.-> export_ExpoRuntimePlan
  export_resolveExpoRuntimeGeneratedAppOutput["resolveExpoRuntimeGeneratedAppOutput"]
  module_src_generatedAppOutput_ts --> export_resolveExpoRuntimeGeneratedAppOutput
  export_resolveExpoRuntimeGeneratedAppOutput -.-> export_ExpoRuntimeGeneratedAppOutputPlan
  export_resolveExpoRuntimeGeneratedAppOutput -.-> export_ExpoRuntimePlan
  export_resolveExpoRuntimeLayoutIntegration["resolveExpoRuntimeLayoutIntegration"]
  module_src_layoutIntegrationPlanning_ts --> export_resolveExpoRuntimeLayoutIntegration
  export_resolveExpoRuntimeLayoutIntegration -.-> export_ExpoRuntimeLayoutIntegrationPlan
  export_resolveExpoRuntimeLayoutIntegration -.-> export_ExpoRuntimePlan
  export_resolveExpoRuntimeNativeOutput["resolveExpoRuntimeNativeOutput"]
  module_src_generatedAppOutput_ts --> export_resolveExpoRuntimeNativeOutput
  export_resolveExpoRuntimeNativeOutput -.-> export_ExpoRuntimeNativeOutputPlan
  export_resolveExpoRuntimeNativeOutput -.-> export_ExpoRuntimePlan
  export_resolveExpoRuntimePlan["resolveExpoRuntimePlan"]
  module_src_resolveExpoRuntimePlan_ts --> export_resolveExpoRuntimePlan
  export_resolveExpoRuntimePlan -.-> export_ExpoRuntimePlan
  export_resolveExpoRuntimeRoutePath["resolveExpoRuntimeRoutePath"]
  module_src_expoActionBridge_ts --> export_resolveExpoRuntimeRoutePath
  export_resolveExpoRuntimeRoutePath -.-> export_ExpoRuntimeRouteResolution
  export_shouldIgnoreBarcodeScan["shouldIgnoreBarcodeScan"]
  module_src_barcodeScanRuntime_ts --> export_shouldIgnoreBarcodeScan
  export_shouldIgnoreBarcodeScan -.-> export_BarcodeScanRecord
